### PR TITLE
fixed typo in translation matrix

### PR DESCRIPTION
**Pull request by marcmorin99**
Was missing two "1" on the diagonal.

### CODE REVIEW

**Comment by marcmorin99** [comment]
I will review the rest of this part since there seems to be an invalid order of the matrices also.

**Comment by pomerlef** [comment]
You can keep it open and add your commit to the same PR.

I confirm for the first typo, good catch!

**Comment by marcmorin99** [comment]
Thanks, I think everything is fine now!

**Comment by pomerlef** [comment]
Yes, I confirm the second correction. Thanks @marcmorin99 !

**Pull request merged**
